<?xml version="1.0" encoding="UTF-8"?>
<tv generator-info-name="WebGrab+Plus/w MDB &amp; REX Postprocess -- version  V3.0.0.0 -- build 3 -- Jan van Straaten" generator-info-url="http://www.webgrabplus.com">
  <channel id="Trojka">
    <display-name lang="sk">Trojka</display-name>
    <icon src="https://www.satelitnatv.sk/obrazky/loga_stanic/50/trojka_50.png" />
    <url>http://www.satelitnatv.sk</url>
  </channel>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Pomôž si sám</title>
    <desc lang="sk">Krvácanie Poskytovanie I. pomoci.(n)</desc>
    <date>1996</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Dovolíte, prosím?</title>
    <desc lang="sk">Voľný čas Relácia o slušnom správaní sa.(n)</desc>
    <date>1996</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Zrkadlo občana Pokorného</title>
    <desc lang="sk">Vojenčina Druhá časť úsmevno-satirického 9-dielneho seriálu zo života dnešného súčasníka, radového občana Maca Pokorného.čb.(n)</desc>
    <date>1967</date>
    <category lang="sk">Seriál</category>
    <country lang="sk">Slovenská republika</country>
    <episode-num system="onscreen">E2/9</episode-num>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Cassovia jazz 1995</title>
    <desc lang="sk">Hudobný projekt Petra Lipu "Naspäť na stromy".(n)</desc>
    <date>1995</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Expedícia Červené more</title>
    <desc lang="sk">Symbióza - život na plytčinách Dokumentárny film o expedícii slovenských potápačov a jachtárov v Červenom mori.(n)</desc>
    <date>1991</date>
    <category lang="sk">Doku</category>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Varím, varíš, varíme</title>
    <desc lang="sk">Ryžovo-mäsové knedličky v kapuste Kulinársky cyklus.(n)</desc>
    <date>1993</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Varím, varíš, varíme</title>
    <desc lang="sk">Ryžovo-mäsové knedličky v kapuste Kulinársky cyklus.(n)</desc>
    <date>1993</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Správy RTVS "N"</title>
    <date>2020</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Nikto neprehrá</title>
    <desc lang="sk">Hádankárska súťaž s Ľubom Belákom.(n)</desc>
    <date>1985</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Malé biblické príbehy</title>
    <desc lang="sk">Kráľ Šalamún.(n)</desc>
    <date>1995</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Za siedmimi horami</title>
    <desc lang="sk">Zlatníci Dokumentárny film o minulosti a súčasnosti zlatníctva na Slovensku.(n)</desc>
    <date>1972</date>
    <category lang="sk">Doku</category>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Na ľudovú nôtu</title>
    <desc lang="sk">Strihový folklórny program.(n)</desc>
    <date>2001</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Správy RTVS "N"</title>
    <date>2020</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Na ľudovú nôtu</title>
    <desc lang="sk">Folklórne pásmo s OĽUN-om.(n)</desc>
    <date>1992</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Kraj pod Rozsutcom</title>
    <desc lang="sk">Dokumentárny film o krásach známej dediny pod Rozsutcom - Terchovej, očami dokumentaristu Milana Koseca.(n)</desc>
    <date>1999</date>
    <category lang="sk">Doku</category>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Senior klub - magazín</title>
    <desc lang="sk">Magazín o aktívnom živote seniorov.(n)</desc>
    <date>2012</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Stretnutie v Tajove</title>
    <desc lang="sk">Publicisticko-zábavný program.(n)</desc>
    <credits>
      <actor>Magda Paveleková</actor>
      <actor>Emília Vášáryová</actor>
      <actor>Karol Konárik</actor>
      <actor>Jozef Adamovič</actor>
      <actor>František Zvarík</actor>
    </credits>
    <date>1979</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Zborovňa</title>
    <desc lang="sk">Trójsky kôň Komediálny seriál.(n)</desc>
    <credits>
      <director>Stanislav Párnický</director>
      <actor>Marián Zednikovič</actor>
      <actor>Ján Kroner</actor>
      <actor>Richard Stanke</actor>
      <actor>Oľga Belešová</actor>
    </credits>
    <date>2002</date>
    <category lang="sk">Seriál</category>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Henrich</title>
    <desc lang="sk">Záznam divadelného predstavenia  drámy Williama Shakespeara z činohry SND.(n)</desc>
    <credits>
      <director>Miloš Pietor</director>
      <actor>Ladislav Chudík</actor>
      <actor>Dušan Jamrich</actor>
      <actor>Emil Horváth ml.</actor>
      <actor>Vladimír Hajdu</actor>
      <actor>Roman Luknár</actor>
      <actor>Juraj Slezáček</actor>
    </credits>
    <date>1987</date>
    <country lang="sk">Slovenská republika</country>
    <episode-num system="onscreen">S4</episode-num>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Chalupárium alebo Keď v meste padla...</title>
    <desc lang="sk">Zábavný program s Michalom Dočolomanským a jeho hosťami na tému - huby, hríby, kuriatka.(n)</desc>
    <credits>
      <actor>Stano Dančiak</actor>
      <actor>Dušan Tarageľ</actor>
      <actor>Ján Majerník</actor>
    </credits>
    <date>2002</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Chvíľa pre pesničku</title>
    <desc lang="sk">Hrá a spieva skupina Javory.(n)</desc>
    <date>1983</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Správy RTVS "N"</title>
    <date>2020</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Na baňu klopajú</title>
    <desc lang="sk">Historická freska zo 16. storočia z obdobia baníckych povstaní v Banskej Štiavnici.(n)</desc>
    <credits>
      <director>Andrej Lettrich</director>
      <actor>Štefan Kvietik</actor>
      <actor>Maroš Kramár</actor>
      <actor>Alojz Kramár</actor>
      <actor>Jana Nagyová</actor>
      <actor>Ľubomír Paulovič</actor>
      <actor>Eva Večerová</actor>
    </credits>
    <date>1981</date>
    <country lang="sk">Československo</country>
    <episode-num system="onscreen">E3/4</episode-num>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Kapitoly z dejín SND</title>
    <desc lang="sk">Čo vatru nietili Dokumentárny film o živote a diele Andreja Bagara.čb.(n)</desc>
    <date>1970</date>
    <category lang="sk">Doku</category>
    <country lang="sk">Československo</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Sluha dvoch pánov</title>
    <desc lang="sk">Klasická komédia Carla Goldoniho - prevzaté predstavenie z divadla SNP v Martine z roku 1991.(n)</desc>
    <credits>
      <director>Matúš Oľha</director>
      <actor>František Výrostko</actor>
      <actor>Ján Kožuch</actor>
      <actor>Martin Horňák</actor>
      <actor>Michal Gazdík</actor>
      <actor>Jozef Domonkoš</actor>
      <actor>Juraj Benčík</actor>
      <actor>Katarína Zatovičová</actor>
      <actor>Eva Gašparová</actor>
    </credits>
    <date>1991</date>
    <category lang="sk">Film</category>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Vydýchnuť</title>
    <desc lang="sk">Poézia Jána Smreka očami režiséra Dušana Trančíka.čb.(n)</desc>
    <date>1970</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Hopla!</title>
    <desc lang="sk">Zábavné domáce videá s Jankom Kronerom.(n)</desc>
    <date>2007</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Varím, varíš, varíme</title>
    <desc lang="sk">Kulinársky cyklus.(n)</desc>
    <date>1993</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Varím, varíš, varíme</title>
    <desc lang="sk">Gombovce a cibliky Kulinársky cyklus.(n)</desc>
    <date>1996</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Recept na každý deň</title>
    <desc lang="sk">Púštny kapor sahara Kulinársky cyklus.(n)</desc>
    <date>2002</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Správy RTVS "N"</title>
    <date>2020</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Nemocnica na okraji mesta</title>
    <desc lang="sk">Percento hnisavých komplikacií Televízny seriál venovaný práci a životu lekárov, zdravotných sestier a ich pacientov v jednej okresnej nemocnici. Scenár: Jaroslav Dietl.(n)</desc>
    <credits>
      <director>Jaroslav Dudek</director>
      <actor>Ladislav Chudík</actor>
      <actor>Miloš Kopecký</actor>
      <actor>Josef Abrhám</actor>
      <actor>Iva Janžurová</actor>
      <actor>Josef Vinklář</actor>
    </credits>
    <category lang="sk">Seriál</category>
    <episode-num system="onscreen">S2 E6/7</episode-num>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">O čom je život podľa...</title>
    <desc lang="sk">Prof. MUDr. Ivan Koza, DrSc hovorí o svojej životnej filozofii.(n)</desc>
    <date>2001</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Chvíľa hudby</title>
    <desc lang="sk">Známe melódie v podaní sláčikového orchestra pod vedením Miroslava Broža.(n)</desc>
    <date>1980</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">411 dní v raji</title>
    <desc lang="sk">Medailón Kornela Földváriho, publicistu a 411 dní riaditeľa Divadla na Korze. Spomienky na účasť v PTP, kde ako syn "buržuja" musel na tri roky narukovať.(n)</desc>
    <date>2004</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Archív Šport RTVS</title>
    <desc lang="sk">MS v hokeji 2002 Štvrťfinále - Kanada - Slovensko.(n)</desc>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Na ľudovú nôtu</title>
    <desc lang="sk">Folklórne pásmo s OĽUN-om.(n)</desc>
    <date>1992</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Kraj pod Rozsutcom</title>
    <desc lang="sk">Dokumentárny film o krásach známej dediny pod Rozsutcom - Terchovej, očami dokumentaristu Milana Koseca.(n)</desc>
    <date>1999</date>
    <category lang="sk">Doku</category>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Henrich</title>
    <desc lang="sk">Záznam divadelného predstavenia  drámy Williama Shakespeara z činohry SND.(n)</desc>
    <credits>
      <director>Miloš Pietor</director>
      <actor>Ladislav Chudík</actor>
      <actor>Dušan Jamrich</actor>
      <actor>Emil Horváth ml.</actor>
      <actor>Vladimír Hajdu</actor>
      <actor>Roman Luknár</actor>
      <actor>Juraj Slezáček</actor>
    </credits>
    <date>1987</date>
    <country lang="sk">Slovenská republika</country>
    <episode-num system="onscreen">S4</episode-num>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Správy RTVS "N"</title>
    <date>2020</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Senior klub - magazín</title>
    <desc lang="sk">Magazín o aktívnom živote seniorov.(n)</desc>
    <date>2012</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Stretnutie v Tajove</title>
    <desc lang="sk">Publicisticko-zábavný program.(n)</desc>
    <credits>
      <actor>Magda Paveleková</actor>
      <actor>Emília Vášáryová</actor>
      <actor>Karol Konárik</actor>
      <actor>Jozef Adamovič</actor>
      <actor>František Zvarík</actor>
    </credits>
    <date>1979</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Zborovňa</title>
    <desc lang="sk">Trójsky kôň Komediálny seriál.(n)</desc>
    <credits>
      <director>Stanislav Párnický</director>
      <actor>Marián Zednikovič</actor>
      <actor>Ján Kroner</actor>
      <actor>Richard Stanke</actor>
      <actor>Oľga Belešová</actor>
    </credits>
    <date>2002</date>
    <category lang="sk">Seriál</category>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Správy RTVS "N"</title>
    <date>2020</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Chvíľa pre pesničku</title>
    <desc lang="sk">Hrá a spieva Malokarpatská kapela.(n)</desc>
    <date>1981</date>
    <country lang="sk">Československo</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Rok v našej prírode</title>
    <desc lang="sk">Život pod končiarmi Život taranskej zveri v zimnom období.(n)</desc>
    <credits>
      <director>Jindro Vlach</director>
    </credits>
    <date>1970</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Senior klub - magazín</title>
    <desc lang="sk">Magazín o aktívnom živote seniorov.(n)</desc>
    <date>2012</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Stretnutie v Prešove</title>
    <desc lang="sk">Zaujatý krásou Prehliadka mesta Prešov so skupinou Modus a Kvetou a Jozefom Stražanovcami.čb.(n)</desc>
    <date>1980</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Zborovňa</title>
    <desc lang="sk">Konope Komediálny seriál.(n)</desc>
    <credits>
      <director>Stanislav Párnický</director>
      <actor>Marián Zednikovič</actor>
      <actor>Ján Kroner</actor>
      <actor>Diana Mórová</actor>
      <actor>Richard Stanke</actor>
      <actor>Oľga Belešová</actor>
      <actor>Zuzana Fialová</actor>
      <actor>Božidara Turzonovová</actor>
    </credits>
    <date>2002</date>
    <category lang="sk">Seriál</category>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Encyklopédia slovenských obcí</title>
    <desc lang="sk">Cerovo Dokumentárny film.(n)</desc>
    <date>1991</date>
    <category lang="sk">Doku</category>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Lakomec</title>
    <desc lang="sk">Prevzaté predstavenie klasickej Moliérovej komédie z Malej scény SND.(n)</desc>
    <credits>
      <director>Peter Mikulík</director>
      <actor>Karol Machata</actor>
      <actor>Maroš Kramár</actor>
      <actor>Zdena Studenková</actor>
      <actor>Ivo Gogál</actor>
      <actor>Zuzana Kocúriková</actor>
      <actor>Mária Kráľovičová</actor>
    </credits>
    <date>1987</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Zahrajte mi takúto</title>
    <desc lang="sk">Ľudová hudba Jaroslava Hrnčiara.(n)</desc>
    <date>1998</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Hopla!</title>
    <desc lang="sk">Zábavné domáce videá s Jankom Kronerom.(n)</desc>
    <date>2007</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Varím, varíš, varíme</title>
    <desc lang="sk">Kulinársky cyklus.(n)</desc>
    <date>1993</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Varím, varíš, varíme</title>
    <desc lang="sk">Gombovce a cibliky Kulinársky cyklus.(n)</desc>
    <date>1996</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Recept na každý deň</title>
    <desc lang="sk">Púštny kapor sahara Kulinársky cyklus.(n)</desc>
    <date>2002</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Správy RTVS "N"</title>
    <date>2020</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Nemocnica na okraji mesta</title>
    <desc lang="sk">Percento hnisavých komplikacií Televízny seriál venovaný práci a životu lekárov, zdravotných sestier a ich pacientov v jednej okresnej nemocnici. Scenár: Jaroslav Dietl.(n)</desc>
    <credits>
      <director>Jaroslav Dudek</director>
      <actor>Ladislav Chudík</actor>
      <actor>Miloš Kopecký</actor>
      <actor>Josef Abrhám</actor>
      <actor>Iva Janžurová</actor>
      <actor>Josef Vinklář</actor>
    </credits>
    <category lang="sk">Seriál</category>
    <episode-num system="onscreen">S2 E6/7</episode-num>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">O čom je život podľa...</title>
    <desc lang="sk">Prof. MUDr. Ivan Koza, DrSc hovorí o svojej životnej filozofii.(n)</desc>
    <date>2001</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Chvíľa hudby</title>
    <desc lang="sk">Známe melódie v podaní sláčikového orchestra pod vedením Miroslava Broža.(n)</desc>
    <date>1980</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">411 dní v raji</title>
    <desc lang="sk">Medailón Kornela Földváriho, publicistu a 411 dní riaditeľa Divadla na Korze. Spomienky na účasť v PTP, kde ako syn "buržuja" musel na tri roky narukovať.(n)</desc>
    <date>2004</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Archív Šport RTVS</title>
    <desc lang="sk">MS v hokeji 2002 Štvrťfinále - Kanada - Slovensko.(n)</desc>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Hopla!</title>
    <desc lang="sk">Zábavné domáce videá s Jankom Kronerom.(n)</desc>
    <date>2007</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Varím, varíš, varíme</title>
    <desc lang="sk">Kulinársky cyklus.(n)</desc>
    <date>1993</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Varím, varíš, varíme</title>
    <desc lang="sk">Krumpier s pecľami Kulinársky cyklus.(n)</desc>
    <date>1996</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Recept na každý deň</title>
    <desc lang="sk">Sójové mäso s pórom Kulinársky program.(n)</desc>
    <date>2002</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Správy RTVS "N"</title>
    <date>2020</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Ja nič neviem</title>
    <desc lang="sk">Pôvodná televízna detektívna hra s nečakaným rozuzlením.(n)</desc>
    <credits>
      <director>Pavol Haspra</director>
      <actor>Soňa Valentová</actor>
      <actor>Marián Geišberg</actor>
      <actor>Matej Landl</actor>
      <actor>Helena Krajčiová</actor>
      <actor>Ivan Laca</actor>
    </credits>
    <date>1998</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Trezor</title>
    <desc lang="sk">Úplný životopis básnika Braxatorisa Z archívov Slovenskej národnej knižnice MS.(n)</desc>
    <date>1996</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Archív Šport  RTVS</title>
    <desc lang="sk">MS v hokeji 2002 Semifinále MS z Goteborgu: Slovensko - Švédsko.(n)</desc>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Chvíľa pre pesničku</title>
    <desc lang="sk">Hrá a spieva Malokarpatská kapela.(n)</desc>
    <date>1981</date>
    <country lang="sk">Československo</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Rok v našej prírode</title>
    <desc lang="sk">Život pod končiarmi Život taranskej zveri v zimnom období.(n)</desc>
    <credits>
      <director>Jindro Vlach</director>
    </credits>
    <date>1970</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Senior klub - magazín</title>
    <desc lang="sk">Magazín o aktívnom živote seniorov.(n)</desc>
    <date>2012</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Stretnutie v Prešove</title>
    <desc lang="sk">Zaujatý krásou Prehliadka mesta Prešov so skupinou Modus a Kvetou a Jozefom Stražanovcami.čb.(n)</desc>
    <date>1980</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Lakomec</title>
    <desc lang="sk">Prevzaté predstavenie klasickej Moliérovej komédie z Malej scény SND.(n)</desc>
    <credits>
      <director>Peter Mikulík</director>
      <actor>Karol Machata</actor>
      <actor>Maroš Kramár</actor>
      <actor>Zdena Studenková</actor>
      <actor>Ivo Gogál</actor>
      <actor>Zuzana Kocúriková</actor>
      <actor>Mária Kráľovičová</actor>
    </credits>
    <date>1987</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Správy RTVS "N"</title>
    <date>2020</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Zborovňa</title>
    <desc lang="sk">Konope Komediálny seriál.(n)</desc>
    <credits>
      <director>Stanislav Párnický</director>
      <actor>Marián Zednikovič</actor>
      <actor>Ján Kroner</actor>
      <actor>Diana Mórová</actor>
      <actor>Richard Stanke</actor>
      <actor>Oľga Belešová</actor>
      <actor>Zuzana Fialová</actor>
      <actor>Božidara Turzonovová</actor>
    </credits>
    <date>2002</date>
    <category lang="sk">Seriál</category>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Encyklopédia slovenských obcí</title>
    <desc lang="sk">Cerovo Dokumentárny film.(n)</desc>
    <date>1991</date>
    <category lang="sk">Doku</category>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Zahrajte mi takúto</title>
    <desc lang="sk">Ľudová hudba Jaroslava Hrnčiara.(n)</desc>
    <date>1998</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Správy RTVS "N"</title>
    <date>2020</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Nech dunia kopytá stád</title>
    <desc lang="sk">Televízny dokument o historickom poslaní koní v súvislosti s ľudskou civilizáciou.(n)</desc>
    <date>1985</date>
    <category lang="sk">Doku</category>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Senior klub - magazín</title>
    <desc lang="sk">Magazín o aktívnom živote, radostiach a starostiach ľudí zrelého veku.(n)</desc>
    <date>2012</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Stretnutie v Tatrách</title>
    <desc lang="sk">Hudobná groteska.(n)</desc>
    <credits>
      <actor>Michal Dočolomanský</actor>
      <actor>Andrej Hryc</actor>
      <actor>Marta Sládečková</actor>
      <actor>Pavol Hammel</actor>
      <actor>Jiří Korn</actor>
      <actor>Věra Špinarová</actor>
    </credits>
    <date>1981</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Zborovňa</title>
    <desc lang="sk">Absencia Komediálny seriál.(n)</desc>
    <credits>
      <director>Stanislav Párnický</director>
      <actor>Marián Zednikovič</actor>
      <actor>Diana Mórová</actor>
      <actor>Richard Stanke</actor>
      <actor>Slávka Halčáková</actor>
    </credits>
    <date>2002</date>
    <category lang="sk">Seriál</category>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Bačova žena</title>
    <desc lang="sk">Televízna inscenácia klasickej slovenskej drámy Ivana Stodolu.(n)</desc>
    <credits>
      <director>Karol L. Zachar</director>
      <actor>Emília Vášáryová</actor>
      <actor>Štefan Kvietik</actor>
      <actor>Michal Dočolomanský</actor>
      <actor>Ladislav Chudík</actor>
      <actor>Oľga Borodáčová</actor>
    </credits>
    <date>1972</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Encyklopédia slovenských obcí</title>
    <desc lang="sk">Žibritov Dokumentárny film.(n)</desc>
    <date>1991</date>
    <category lang="sk">Doku</category>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Zahrajte mi takúto</title>
    <desc lang="sk">Hudobno-zábavná relácia venovaná folklóru. Hrá dychová hudba Dubovanka z Dubovian.(n)</desc>
    <date>1998</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Hopla!</title>
    <desc lang="sk">Zábavné domáce videá s Jankom Kronerom.(n)</desc>
    <date>2007</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Varím, varíš, varíme</title>
    <desc lang="sk">Kulinársky cyklus.(n)</desc>
    <date>1993</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Varím, varíš, varíme</title>
    <desc lang="sk">Krumpier s pecľami Kulinársky cyklus.(n)</desc>
    <date>1996</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Recept na každý deň</title>
    <desc lang="sk">Sójové mäso s pórom Kulinársky program.(n)</desc>
    <date>2002</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Správy RTVS "N"</title>
    <date>2020</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Ja nič neviem</title>
    <desc lang="sk">Pôvodná televízna detektívna hra s nečakaným rozuzlením.(n)</desc>
    <credits>
      <director>Pavol Haspra</director>
      <actor>Soňa Valentová</actor>
      <actor>Marián Geišberg</actor>
      <actor>Matej Landl</actor>
      <actor>Helena Krajčiová</actor>
      <actor>Ivan Laca</actor>
    </credits>
    <date>1998</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Trezor</title>
    <desc lang="sk">Úplný životopis básnika Braxatorisa Z archívov Slovenskej národnej knižnice MS.(n)</desc>
    <date>1996</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Archív Šport  RTVS</title>
    <desc lang="sk">MS v hokeji 2002 Semifinále MS z Goteborgu: Slovensko - Švédsko.(n)</desc>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Hopla!</title>
    <desc lang="sk">Zábavné domáce videá s Jankom Kronerom.(n)</desc>
    <date>2007</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Varím, varíš, varíme</title>
    <desc lang="sk">Kulinársky cyklus.(n)</desc>
    <date>1993</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Varím, varíš, varíme</title>
    <desc lang="sk">Kysnuté rohy Kulinársky cyklus.(n)</desc>
    <date>1996</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Recept na každý deň</title>
    <desc lang="sk">Vrabčie hniezda Kulinársky cyklus.(n)</desc>
    <date>2002</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Správy RTVS "N"</title>
    <date>2020</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Soirée z Mlynskej doliny</title>
    <desc lang="sk">Stretnutie s Evou Pavlíkovou a jej televíznymi postavami.(n)</desc>
    <date>2001</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Mojich sedem divov</title>
    <desc lang="sk">Zdeněk Horský Publicisticko-vzdelávacia relácia, v ktorej hosť pútavým spôsobom zoznamuje divákov so siedmimi vecami, ktoré ho najviac udivujú.(n)</desc>
    <date>1988</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Okná vesmíru dokorán</title>
    <desc lang="sk">S tiažou je to ťažké Einsteinova teória o deformovanosti zakrivení priestoru s Jiřím Grygarom.(n)</desc>
    <date>1983</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Bratislavské miniatúry</title>
    <desc lang="sk">Bratislava mesto - Braslava civitas.(n)</desc>
    <date>1996</date>
    <country lang="sk">Slovenská republika</country>
  </programme>
  <programme start="20200330000000 +0200" stop="20200330000000 +0200" channel="Trojka">
    <title lang="sk">Archív Šport RTVS</title>
    <desc lang="sk">MS v hokeji 2002 Finále z Goteborgu: Slovensko - Rusko.(n)</desc>
  </programme>
</tv>